### ISSUE TITLE
Torrent detail expansion is positionally dependent

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/receptor#18]
Specifically:
* select torrent A
* toggle torrent A's files
* select torrent B

At this point, torrent B's files will be opened, and torrent A's files will not be. Upon unselecting torrent B, torrent A's files will be open as expected.

**Comment by SirCmpwn** [comment]
Note for when I get around to this: the solution should be to add a key prop here https://github.com/SirCmpwn/receptor/blob/master/src/ui/torrent_details.js#L310
