### ISSUE TITLE
File download token doesn't update

### ISSUE THREAD

**Issue by Luminarys** [SirCmpwn/receptor#44]
Because the token is extracted from the server resource without subscribing to it, when the token actually updates the component will never re-render.

**Comment by SirCmpwn** [comment]
We subscribe to literally every resource synapse sends us, including the server.

**Comment by SirCmpwn** [comment]
https://github.com/SirCmpwn/receptor/blob/master/src/socket.js#L39

**Comment by SirCmpwn** [comment]
If we weren't subscribed to the server things like the global upload/download rate wouldn't update, either.
