### ISSUE TITLE
Submodule changed location

### ISSUE THREAD

**Issue by RunningDroid** [SirCmpwn/receptor#53]
The submodule at scss/srht appears to have moved from https://git.sr.ht/~sircmpwn/srht/ to https://git.sr.ht/~sircmpwn/core.sr.ht/

Git error:

> Fetching origin
> Fetching submodule scss/srht
> fatal: repository 'https://git.sr.ht/~sircmpwn/srht/' not found
> error: Could not fetch origin

**Comment by SirCmpwn** [comment]
Thanks, just pushed a fix.
